# Generated by Django 4.2.20 on 2025-09-17 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_genre', models.CharField(blank=True, choices=[('fantasy', 'Fantasy'), ('sci_fi', 'Science Fiction'), ('romance', 'Romance'), ('horror', 'Horror'), ('mystery', 'Mystery'), ('adventure', 'Adventure'), ('drama', 'Drama'), ('comedy', 'Comedy')], max_length=20)),
                ('preferred_length', models.CharField(blank=True, choices=[('short', 'Short'), ('medium', 'Medium'), ('long', 'Long')], max_length=10)),
                ('preferred_tone', models.CharField(blank=True, choices=[('happy', 'Happy'), ('dark', 'Dark'), ('humorous', 'Humorous'), ('dramatic', 'Dramatic'), ('mysterious', 'Mysterious'), ('romantic', 'Romantic')], max_length=15)),
                ('stories_generated', models.IntegerField(default=0)),
                ('favorite_stories_count', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
