# Generated by Django 4.2.20 on 2025-09-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell us about yourself', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_genre',
            field=models.CharField(blank=True, choices=[('fantasy', 'Fantasy'), ('sci_fi', 'Science Fiction'), ('romance', 'Romance'), ('horror', 'Horror'), ('mystery', 'Mystery'), ('adventure', 'Adventure'), ('drama', 'Drama'), ('comedy', 'Comedy')], max_length=20),
        ),
    ]
