[phases.setup]
nixPkgs = ["python312", "pip"]

[phases.install]
cmd = "pip install -r requirements.txt --no-cache-dir"

[phases.build]
cmd = "python manage.py collectstatic --noinput --clear"

[start]
cmd = "gunicorn story_generator.wsgi:application --bind 0.0.0.0:$PORT" 