[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 

[variables]
PYTHON_VERSION = "3.12"
PIP_NO_CACHE_DIR = "1" 