# Generated by Django 4.2.20 on 2025-09-17 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('keywords', models.CharField(help_text='Keywords for story generation', max_length=500)),
                ('genre', models.CharField(choices=[('fantasy', 'Fantasy'), ('sci_fi', 'Science Fiction'), ('romance', 'Romance'), ('horror', 'Horror'), ('mystery', 'Mystery'), ('adventure', 'Adventure'), ('drama', 'Drama'), ('comedy', 'Comedy')], default='fantasy', max_length=20)),
                ('length', models.CharField(choices=[('short', 'Short (100-300 words)'), ('medium', 'Medium (300-600 words)'), ('long', 'Long (600-1000 words)')], default='short', max_length=10)),
                ('tone', models.CharField(choices=[('happy', 'Happy'), ('dark', 'Dark'), ('humorous', 'Humorous'), ('dramatic', 'Dramatic'), ('mysterious', 'Mysterious'), ('romantic', 'Romantic')], default='happy', max_length=15)),
                ('content', models.TextField(help_text='Generated story content')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False, help_text='Make story public in gallery')),
                ('is_favorite', models.BooleanField(default=False, help_text='User marked as favorite')),
                ('rating', models.IntegerField(blank=True, help_text='User rating 1-5', null=True)),
                ('generation_time', models.FloatField(blank=True, help_text='Time taken to generate in seconds', null=True)),
                ('ai_model_used', models.CharField(default='gpt-3.5-turbo', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
