# Generated by Django 4.2.20 on 2025-09-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_storycollection_story_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='rating',
            field=models.IntegerField(default=0, help_text='User rating 0-5 (0=unrated)'),
        ),
    ]
